ALTER TABLE IF EXISTS students
  ADD COLUMN IF NOT EXISTS year INT,
  ADD COLUMN IF NOT EXISTS academic_year VARCHAR(20),
  ADD COLUMN IF NOT EXISTS section VARCHAR(10),
  ADD COLUMN IF NOT EXISTS subsection VARCHAR(10),
  ADD COLUMN IF NOT EXISTS mentor_id INT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mentor_email VARCHAR(150),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE students
SET year = CEIL(semester::numeric / 2)::int
WHERE year IS NULL
  AND semester IS NOT NULL;

CREATE TABLE IF NOT EXISTS mentor_allocations (
  id SERIAL PRIMARY KEY,
  year INT,
  academic_year VARCHAR(20) NOT NULL DEFAULT '',
  semester INT NOT NULL,
  section VARCHAR(10) NOT NULL,
  subsection VARCHAR(10) NOT NULL,
  mentor_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mentor_name VARCHAR(150) NOT NULL,
  mentor_email VARCHAR(150) NOT NULL,
  created_by_hod INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE mentor_allocations
  ADD COLUMN IF NOT EXISTS year INT,
  ALTER COLUMN academic_year SET DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_mentor_allocations_unique_cohort
ON mentor_allocations (academic_year, semester, UPPER(section), UPPER(subsection));

CREATE TABLE IF NOT EXISTS notifications (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50),
  reference_id INT,
  reference_type VARCHAR(50),
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS reference_id INT,
  ADD COLUMN IF NOT EXISTS reference_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;

ALTER TABLE IF EXISTS projects
  ADD COLUMN IF NOT EXISTS academic_year VARCHAR(20),
  ADD COLUMN IF NOT EXISTS semester INT,
  ADD COLUMN IF NOT EXISTS section VARCHAR(10),
  ADD COLUMN IF NOT EXISTS subsection VARCHAR(10);

ALTER TABLE IF EXISTS teams
  ADD COLUMN IF NOT EXISTS mentor_id INT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mentor_email VARCHAR(150);

ALTER TABLE IF EXISTS submissions
  ADD COLUMN IF NOT EXISTS mentor_id INT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mentor_email VARCHAR(150);

ALTER TABLE IF EXISTS project_groups
  ADD COLUMN IF NOT EXISTS mentor_id INT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mentor_email VARCHAR(150);

ALTER TABLE IF EXISTS project_form_submissions
  ADD COLUMN IF NOT EXISTS mentor_id INT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mentor_email VARCHAR(150);

ALTER TABLE IF EXISTS registration_form_submissions
  ADD COLUMN IF NOT EXISTS mentor_id INT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mentor_email VARCHAR(150);
