export const queryKeys = {
  authMe: ['auth', 'me'],
  studentProfile: ['student', 'profile'],
  registrationForms: (params = {}) => ['registrationForms', params],
  studentNotifications: (params = {}) => ['studentNotifications', params],
  hodSubmissions: (params = {}) => ['hodSubmissions', params],
  hodStudents: (params = {}) => ['hodStudents', params],
  hodProjects: (params = {}) => ['hodProjects', params],
  hodMentors: ['hodMentors'],
  hodMentorAllocations: ['hodMentorAllocations'],
  hodStats: ['hodStats'],
  mentorTeams: ['mentorTeams'],
  mentorAllocatedStudents: ['mentorAllocatedStudents'],
  mentorReviews: ['mentorReviews'],
  timelines: ['timelines'],
  milestones: ['milestones'],
  projects: ['projects'],
};
